#
# Generated by XPact v2.17
#

# Path to the top folder
TOP:=.

# Current path from top folder
CURRENT:=.

# Path to the component containing this folder
COMPONENT_TOP:=.

# Name of the user's makefile
UserMakefile:=trdp

# This unit to build
UNITURI:=thirdparty.protocol.trdp
thirdparty.protocol.trdp.PATH:=$(TOP)

# Make rules chosen
tools.pactMake.PATH:=$(TOP)/import/tools.pactMake

TOOLPATH:=$(tools.pactMake.PATH)
# Including the pactMake's entry point
include $(TOOLPATH)/make/main.mak

# List subdirs to build all dependant components
DEPS_SUBDIRS = \
   import/thirdparty.zlib/ \
   import/thirdparty.libxml2/ \
